services:
  transcriber:
    restart: unless-stopped
    image: rsdo/ds2/nemo-asr:latest
    build: .
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./models/v2.0
        target: /opt/asr/models/v2.0
        read_only: true
